Repository WorkshopMDS/vivatech-back, pull requests merged in 2023-05, with the labels that each got.

#1 story/WOR-42/configuration-et-securisation-des-acces-api
  .env.sample
  .eslintrc.js
  .github/workflows/pull_requests.yml
  Makefile
  README.md
  jest.config.js
  nodemon.json
  package.json
  src/__tests__/Users.test.ts
  src/__tests__/configs/setup.ts
  src/__tests__/user.test.ts
  src/app.ts
  src/controllers/index.ts
  src/controllers/user.controller.ts
  src/controllers/user.controllers.ts
  src/middlewares/auth.middleware.ts
  src/middlewares/permission.middleware.ts
  src/models/user.model.ts
  src/router.ts
  src/routes/user.routes.ts
  src/types/global.type.ts
  src/types/user.ts
  src/types/user.type.ts
  src/utils/errors.ts
  src/utils/functions.ts
  src/utils/roles.ts
  yarn.lock
Labels: PR: REVIEW OK

#3 story/WOR-43/fix-des-retours-de-pr-du-ticket-wor-42
  .eslintrc.js
  .github/workflows/pull_requests.yml
  jest.config.js
  package.json
  src/__tests__/user.test.ts
  src/controllers/user.controllers.ts
  src/middlewares/auth.middleware.ts
  src/models/user.model.ts
  src/routes/user.routes.ts
  src/utils/errors.ts
  src/utils/functions.ts
  yarn.lock
Labels: PR: REVIEW OK, effort: small

#5 story/WOR-11/verification-du-numero-de-ticket-cote-api
  src/__tests__/ticket.test.ts
  src/controllers/ticket.controllers.ts
  src/controllers/user.controllers.ts
  src/models/ticket.model.ts
  src/router.ts
  src/routes/index.ts
  src/routes/ticket.routes.ts
  src/types/ticket.type.ts
  src/utils/errors.ts
Labels: PR: REVIEW OK

#6 story/WOR-36/creer-le-model-de-donnee-routes-pour-les-speaker
  src/__tests__/configs/functions.ts
  src/__tests__/speaker.test.ts
  src/__tests__/user.test.ts
  src/controllers/user.controllers.ts
  src/middlewares/auth.middleware.ts
  src/models/user.model.ts
  src/routes/user.routes.ts
  src/types/global.type.ts
  src/types/user.type.ts
  src/utils/roles.ts
Labels: PR: REVIEW OK, effort: small

#7 story/WOR-17/recuperation-des-exposants-cote-api
  .eslintrc.js
  .gitignore
  package.json
  src/__tests__/configs/functions.ts
  src/__tests__/exhibitor.test.ts
  src/__tests__/mockups/error.mock.ts
  src/__tests__/mockups/exhibitor.mock.ts
  src/__tests__/ticket.test.ts
  src/__tests__/user.test.ts
  src/controllers/exhibitor.controller.ts
  src/controllers/user.controller.ts
  src/environments/errors.environment.ts
  src/environments/httpStatusCodes.environment.ts
  src/middlewares/auth.middleware.ts
  src/middlewares/errorHandler.middleware.ts
  src/models/exhibitor.model.ts
  src/responses/api.response.ts
  src/router.ts
  src/routes/default.route.ts
  src/routes/exhibitor.route.ts
  src/routes/index.ts
  src/routes/ticket.route.ts
  src/routes/user.route.ts
  src/types/exhibitor.type.ts
  src/types/global.type.ts
  src/types/user.type.ts
  yarn.lock
Labels: PR: REVIEW OK

#8 story/WOR-48/refactor-droits-et-erreurs
  src/__tests__/configs/functions.ts
  src/__tests__/exhibitor.test.ts
  src/__tests__/mockups/error.mock.ts
  src/__tests__/mockups/exhibitor.mock.ts
  src/__tests__/speaker.test.ts
  src/__tests__/ticket.test.ts
  src/__tests__/user.test.ts
  src/controllers/exhibitor.controller.ts
  src/controllers/ticket.controllers.ts
  src/controllers/user.controller.ts
  src/middlewares/auth.middleware.ts
  src/middlewares/errorHandler.middleware.ts
  src/middlewares/permission.middleware.ts
  src/models/exhibitor.model.ts
  src/routes/default.route.ts
  src/routes/exhibitor.route.ts
  src/routes/user.route.ts
  src/utils/apiResponse.ts
  src/utils/errors.ts
Labels: PR: REVIEW OK

#11 feat(cv): create cv model and routes
  src/controllers/cv.controller.ts
  src/controllers/ticket.controllers.ts
  src/models/cv.model.ts
  src/router.ts
  src/routes/cv.route.ts
  src/routes/index.ts
  src/types/cv.type.ts
  src/types/user.type.ts
Labels: PR: Review TODO

#13 WOR-22-cache
  package.json
  src/controllers/conference.controller.ts
  src/controllers/cv.controller.ts
  src/controllers/exhibitor.controller.ts
  src/controllers/interest.controller.ts
  src/environments/constants.environment.ts
  src/router.ts
  src/utils/cacheClear.ts
  yarn.lock
Labels: PR: Review TODO

#14 bug/WOR-66/return-user-data-to-base-64-instead-of-jwt-sign
  src/controllers/ticket.controllers.ts
Labels: PR: Review TODO

#15 bug/WOR-67/fix-get-to-post-for-check-code-method
  src/routes/ticket.route.ts
Labels: PR: Review TODO

#16 bug/WOR-72/ajouter-lid-dans-le-retours-des-conferences
  src/controllers/conference.controller.ts
Labels: PR: REVIEW OK

#17 Story/wor 37/creation de parcours cote api
  src/controllers/exhibitor.controller.ts
  src/controllers/journey.controller.ts
  src/models/conference.model.ts
  src/models/journey.model.ts
  src/router.ts
  src/routes/index.ts
  src/routes/journey.route.ts
  src/types/conference.type.ts
  src/types/exhibitor.type.ts
  src/types/global.type.ts
  src/types/journey.type.ts
  src/types/user.type.ts
  yarn.lock
Labels: PR: Review TODO

#18 refactor: add interests to users and conferences to match KYC
  src/controllers/conference.controller.ts
  src/controllers/journey.controller.ts
  src/controllers/user.controller.ts
  src/models/conference.model.ts
  src/models/user.model.ts
  src/types/conference.type.ts
  src/types/user.type.ts
Labels: PR: REVIEW OK

#19 refactor: added user\'s parcours score
  src/models/user.model.ts
  src/types/user.type.ts
Labels: PR: REVIEW OK

#20 refactor: correctly set a global cache to be able to clean it at once
  src/controllers/conference.controller.ts
  src/controllers/cv.controller.ts
  src/controllers/exhibitor.controller.ts
  src/controllers/interest.controller.ts
  src/controllers/journey.controller.ts
  src/utils/cacheClear.ts
Labels: PR: REVIEW OK
